# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlickerImagesMapFinal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlickerImagesMapFinal

  target 'FlickerImagesMapFinalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlickerImagesMapFinalUITests' do
    # Pods for testing
  end
pod 'GoogleMaps'
end
